import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import * as api from "./api";
import "./styles.css";
const scopes=["available","mine","answered","expired"] as const;

function Login({onLogin}:{onLogin:(session:{user:api.User;csrf_token:string})=>void}){
 const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);
 async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{onLogin(await api.login(email,password));}catch(reason){setError(reason instanceof Error?reason.message:"Login failed");}finally{setBusy(false);}}
 return <main className="login"><div className="brand">H</div><p className="eyebrow">HUMAN API</p><h1>Authorized responder queue</h1><p>Messages in this queue are submitted by API callers and may contain sensitive or misleading content. Access only for your assigned response duties.</p><form onSubmit={submit}><label>Email<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" autoComplete="current-password" minLength={10} value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<p role="alert" className="error">{error}</p>}<button disabled={busy}>{busy?"Signing in…":"Sign in"}</button></form></main>;
}

function Editor({question,csrf,onDone}:{question:api.Question;csrf:string;onDone:()=>void}){
 const[content,setContent]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");
 useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(content.trim()){event.preventDefault();event.returnValue="";}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[content]);
 const preview=useMemo(()=>JSON.stringify({id:question.completion_id,content},null,2),[question.completion_id,content]);
 async function submit(){if(!content.trim()||busy)return;setBusy(true);setError("");try{await api.answer(question.id,content,csrf);setContent("");onDone();}catch(reason){setError(reason instanceof Error?reason.message:"Answer failed");setBusy(false);}}
 return <section className="editor"><div className="section-title"><div><p className="eyebrow">HUMAN ANSWER JSON</p><h3>Write the semantic answer</h3></div><span>{content.length.toLocaleString()} / 50,000</span></div><div className="json-form"><span>{"{"}</span><div className="json-line"><code>"id"</code><span>:</span><input data-testid="human-answer-id" aria-label="id" value={question.completion_id} readOnly/><button className="copy" type="button" onClick={()=>navigator.clipboard.writeText(question.completion_id)}>Copy ID</button><span>,</span></div><div className="json-line content-line"><code>"content"</code><span>:</span><textarea data-testid="human-answer-content" aria-label="content" value={content} onChange={e=>setContent(e.target.value)} maxLength={50000} rows={8}/></div><span>{"}"}</span></div><details><summary>Read-only valid JSON preview</summary><pre data-testid="human-answer-json-preview">{preview}</pre></details>{error&&<p role="alert" className="error">{error}</p>}<button data-testid="human-answer-submit" className="primary" type="button" disabled={!content.trim()||busy} onClick={submit}>{busy?"Submitting…":"Submit human answer"}</button></section>;
}

function Queue({session}:{session:{user:api.User;csrf_token:string}}){
 const[scope,setScope]=useState<(typeof scopes)[number]>("available");const[questions,setQuestions]=useState<api.Question[]>([]);const[selected,setSelected]=useState<string|null>(null);const[error,setError]=useState("");
 const refresh=useCallback(async()=>{try{setQuestions((await api.list(scope)).data);}catch(reason){setError(reason instanceof Error?reason.message:"Queue failed");}},[scope]);
 useEffect(()=>{void refresh();const poll=window.setInterval(()=>void refresh(),3000);const beat=window.setInterval(()=>void api.heartbeat(session.csrf_token),15000);void api.heartbeat(session.csrf_token);return()=>{clearInterval(poll);clearInterval(beat);};},[refresh,session.csrf_token]);
 const active=questions.find(q=>q.id===selected&&q.is_mine);
 async function claim(question:api.Question){try{await api.claim(question.id,session.csrf_token);setSelected(question.id);setScope("mine");await refresh();}catch(reason){setError(reason instanceof Error?reason.message:"Claim conflict");await refresh();}}
 return <main><header><div><p className="eyebrow">SHARED RESPONSE OPERATIONS</p><h1>Human API Queue</h1><p className="muted">Signed in as {session.user.email}. Answers are human-written; callers' messages may be read and stored for queue operation and audit.</p></div><div className="live"><i/>Live polling</div></header><nav>{scopes.map(value=><button key={value} className={scope===value?"active":""} onClick={()=>{setScope(value);setSelected(null);}}>{value[0].toUpperCase()+value.slice(1)}</button>)}</nav>{error&&<p role="alert" className="error">{error}</p>}<div className="layout"><section className="cards">{questions.length===0&&<div className="empty">No questions in this view.</div>}{questions.map(question=><article key={question.id} className={selected===question.id?"selected":""}><div className="card-top"><code>{question.completion_id}</code><span>{question.status}</span></div><p className="meta">{question.model} · {new Date(question.created_at).toLocaleString()}</p><div className="conversation">{question.messages.map(message=><div key={message.position}><strong>{message.role}</strong><p>{message.content}</p></div>)}</div>{question.status==="pending"&&<button data-testid="human-question-claim" className="primary" onClick={()=>claim(question)}>Claim</button>}{question.is_mine&&<div className="actions"><button className="primary" onClick={()=>setSelected(question.id)}>Answer</button><button data-testid="human-question-release" onClick={async()=>{await api.release(question.id,session.csrf_token);setSelected(null);await refresh();}}>Release</button></div>}</article>)}</section>{active&&<Editor question={active} csrf={session.csrf_token} onDone={()=>{setSelected(null);setScope("answered");void refresh();}}/>}</div></main>;
}

export function App(){const[session,setSession]=useState<{user:api.User;csrf_token:string}|null>(null);const[checking,setChecking]=useState(true);useEffect(()=>{api.me().then(setSession).catch(()=>undefined).finally(()=>setChecking(false));},[]);if(checking)return <main><p>Loading…</p></main>;return session?<Queue session={session}/>:<Login onLogin={setSession}/>;}
